# 任意のワークフロー名
name: End-to-end tests
# トリガーするイベントを設定。この場合はpush
# 参考: https://docs.github.com/ja/actions/reference/events-that-trigger-workflows#example-workflow-configuration
on: [push]
jobs:
  # 任意のジョブ名を指定
  cypress-run:
    # 使用するランナーを指定。
    # Cypress公式が20.04を指定しているので合わせているが、どのバージョンでも問題ないはず
    runs-on: ubuntu-20.04
    steps:
      # リポジトリをチェックアウトし、ワークフローがリポジトリにアクセスできるようにする
      # 参考: https://github.com/actions/checkout
      - name: Checkout
        uses: actions/checkout@v3

      # # Next.jsアプリを起動
      - name: Start App
        run: |
          npm ci
          npm run build
          npm run preview

      # cypress-io/github-action@v2 を使用してCypressを実行
      - name: Cypress run
        uses: cypress-io/github-action@v5
        with:
          browser: chrome
          wait-on: "http://localhost:4173"
      # # 任意
      # # Cypress実行時に生成されたビデオとスクリーンショットを保存できる
      # # 参考: https://github.com/cypress-io/github-action#artifacts
      # - uses: actions/upload-artifact@v2
      #   if: always()
      #   with:
      #     name: Cypress E2E Videos
      #     path: e2e/cypress/videos
